vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        profiles:
            uri_prefix: /resources/media/admin/profiles
            upload_destination: '%kernel.project_dir%/public/resources/media/admin/profiles'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer